/**
 * Core data types for ROOTS app
 */

export interface FamilyTree {
  id: string;
  name: string;
  description: string;
  treeScore: number; // Total points earned from all logs
  logCount: number; // Number of logs (for tree growth stages)
  members: Person[];
  activities: ActivityStats;
  completedActivities?: CompletedActivity[]; // Track completed activities with timestamps
  lastActivityDate?: string; // ISO date string of last completed activity
}

export interface Person {
  id: string;
  name: string;
  role: string; // e.g., "Dad", "Sibling", "Grandfather"
  birthYear?: number;
  generation: number; // Calculated based on distance from root person
  avatarColor: string; // For placeholder avatars
  initials: string;
  gender?: 'male' | 'female' | 'other'; // Gender for proper labels
  parentIds?: string[]; // IDs of parents (max 2)
  spouseId?: string; // ID of spouse/partner
}

export interface ActivityStats {
  completed: number;
  skipped: number;
}

export type ActivityCategory = 'bonding' | 'fun' | 'learning' | 'health' | 'creative' | 'outdoor';

export interface Activity {
  id: string;
  title: string;
  description: string;
  category: ActivityCategory;
  duration: string; // e.g., "30 mins", "1-2 hours"
  tags: string[];
  aiGenerated?: boolean; // True if generated by AI
  generatedFrom?: string; // ID of activity this was inspired by
}

export interface CompletedActivity {
  activityId: string;
  completedAt: string; // ISO date string
  participantIds: string[]; // Which family members participated
}

export interface Photo {
  id: string;
  url: string; // Base64 data URL for uploaded images
  caption: string;
  color: string; // For placeholder colored boxes
}

export interface DiscardedPhoto {
  photo: Photo; // The original photo data
  discardedAt: string; // ISO date string when photo was discarded
  expiresAt: string; // ISO date string (30 days from discardedAt)
  reason: 'duplicate' | 'manual'; // Why it was discarded
  duplicateOf?: string; // Photo ID this is a duplicate of (if reason is 'duplicate')
  similarityScore?: number; // 0-100, how similar to the original (if duplicate)
  sourceAlbumId: string; // Which album it came from
  sourceMemoryId: string; // Which memory it came from
  sourceMemoryTitle: string; // Memory title for context
}

export interface Memory {
  id: string;
  title: string; // e.g., "Beach Day", "Theme Park Visit"
  date: string; // e.g., "July 15, 2024"
  photos: Photo[];
}

export interface Album {
  id: string;
  title: string; // e.g., "Summer Vacation 2024"
  description: string;
  coverColor: string; // For album cover
  lastUpdated: string; // e.g., "2 days ago"
  memories: Memory[]; // Contains individual memories
}

// Legacy type - keeping for backward compatibility
export interface MemoryCollection {
  id: string;
  title: string;
  photoCount: number;
  lastUpdated: string;
  photos: Photo[];
}

export interface CheckIn {
  id: string;
  personId: string;
  personName: string;
  mood: number; // 1-5
  emoji: string;
  note?: string;
  timestamp: string; // ISO date string
  treeId: string;
}

export interface PositiveMoment {
  id: string;
  activityName?: string;
  participantIds: string[]; // Who was involved (family members)
  additionalPeople?: string; // Extended family or others
  date: string; // ISO date string
  emotionRating?: number; // 1-5
  notes?: string;
  photos: Photo[]; // Array of photos
  pointsEarned: number; // 1-6 based on details provided
  timestamp: string; // When it was logged
  treeId: string;
  starred?: boolean; // If user favorited this log
}

export interface AppState {
  activeFamilyTreeId: string;
  trees: FamilyTree[];
  activitySuggestions: Activity[];
  memoryCollections: Record<string, MemoryCollection[]>; // keyed by tree id - legacy
  albums: Record<string, Album[]>; // keyed by tree id - new structure
  lastExpandedMemory: Record<string, string | null>; // keyed by tree id
  lastExpandedAlbum: Record<string, string | null>; // keyed by tree id
  checkIns: CheckIn[]; // All check-ins across all trees
  notifications: CheckIn[]; // Recent check-ins to notify about
  positiveMoments: PositiveMoment[]; // All logged positive moments
  discardedPhotos: DiscardedPhoto[]; // Photos in discard bin (30-day recovery)
}
